### ISSUE TITLE
"use_linked_clone" fails in parallel mode

### ISSUE THREAD

**Issue by legal90** [Parallels/vagrant-parallels#206]
If you run `vagrant up` for the first time in multi-machine configuration, it fails with error telling that `prlctl clone --linked` couldn't be executed concurrently. It mostly like a Parallels Desktop issue, but should be worked around on the "vagrant-parallels" side.

Vagrantfile:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "parallels/centos-6.6"

  config.vm.define "centos_1"
  config.vm.define "centos_2"
  config.vm.define "centos_3"

  config.vm.provider "parallels" do |prl|
    prl.use_linked_clone = true
  end
end
```

```console
$ vagrant up

<...>

An error occurred while executing the action on the 'centos_3'
machine. Please handle this error then try again:

There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlctl", "clone", "centos-6.6-x86_64", "--name", "centos-6.6-x86_64_1440573847293_55601", "--linked", "--id", "66adbac3-9fa7-410f-bbad-3ac58fa6f8f1"]

Stderr:
Failed to clone the VM: The virtual machine could not be found. The virtual machine is not registered in the virtual machine directory on your Mac. Contact the Parallels support team for assistance.
```
Parallels Desktop 11.0.0 (31193)
vagrant-parallels v1.4.2

**Comment by legal90** [comment]
Fixed in [v1.4.3](https://github.com/Parallels/vagrant-parallels/releases/tag/v1.4.3)

**Comment by tradel** [comment]
Still an issue in 1.7.8.

First machine errored with:
```
Command: ["/usr/local/bin/prlctl", "unregister", "0b2fbbe0-8bd7-452d-94e6-f2f2c2b9941d"]

Stderr: Failed to unregister the VM: Unable to perform the action because the virtual machine is busy. The virtual machine is being cloned. Please try again later.
```

Second machine errored with:
```
padding error, need 74192792 block 16
```

**Comment by max-arnold** [comment]
I also often get hit by this:

```
Command: ["/usr/local/bin/prlctl", "unregister", "e75da2c8-df22-4562-ba86-8ba81c3dbbe9"]

Stderr: Failed to unregister the VM: Unable to perform the action because the virtual machine is busy. The virtual machine is being cloned. Please try again later.
```

```
% vagrant version
Installed Version: 2.2.9
Latest Version: 2.2.9

% vagrant plugin list
vagrant-parallels (2.0.1, global)
```

Parallels  15.1.4 (47270)

**Comment by cecilphillip** [comment]
I'm get this error too. Using the same versions as @max-arnold 
cc @legal90

**Comment by max-arnold** [comment]
@tradel @cecilphillip I just upgraded to [2.1.0](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.1.0) and it looks like the issue was fixed in https://github.com/Parallels/vagrant-parallels/pull/370
