### ISSUE TITLE
Cannot do fresh install of Vagrant 2.2.7 and vagrant-parallels on MacOS 10.15.2

### ISSUE THREAD

**Issue by carcus88** [Parallels/vagrant-parallels#348]
To preface Vagrant 2.2.6 works just fine.

When I install Vagrant 2.2.7 and then run ```vagrant plugin install vagrant-parallels``` I get the following

```
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Fetching: mini_portile2-2.4.0.gem (100%)
Fetching: nokogiri-1.10.7.gem (100%)
Building native extensions.  This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/markmitchell/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -r ./siteconf20200130-3346-738d4e.rb extconf.rb
checking if the C compiler accepts -arch i386 -arch x86_64 -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/markmitchell/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/markmitchell/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7 for inspection.
Results logged to /Users/markmitchell/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.7/gem_make.out

```

The output of gem_make.out is as follows

```
"clang -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -arch i386 -arch x86_64 -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib     -lruby.2.4.9  -lpthread -ldl -lobjc  "
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:102:37: error: 'ruby_check_sizeof_long' declared as an array with a negative size
typedef char ruby_check_sizeof_long[SIZEOF_LONG == sizeof(long) ? 1 : -1];
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:58:21: note: expanded from macro 'SIZEOF_LONG'
#define SIZEOF_LONG 8
                    ^
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:106:38: error: 'ruby_check_sizeof_voidp' declared as an array with a negative size
typedef char ruby_check_sizeof_voidp[SIZEOF_VOIDP == sizeof(void*) ? 1 : -1];
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:63:22: note: expanded from macro 'SIZEOF_VOIDP'
#define SIZEOF_VOIDP 8
                     ^
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1615:5: error: __int128 is not supported on this target
    DSIZE_T c2 = (DSIZE_T)a * (DSIZE_T)b;
    ^
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1606:18: note: expanded from macro 'DSIZE_T'
# define DSIZE_T uint128_t
                 ^
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:183:28: note: expanded from macro 'uint128_t'
#define uint128_t unsigned __int128
                           ^
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1615:19: error: __int128 is not supported on this target
    DSIZE_T c2 = (DSIZE_T)a * (DSIZE_T)b;
                  ^
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1606:18: note: expanded from macro 'DSIZE_T'
# define DSIZE_T uint128_t
                 ^
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:183:28: note: expanded from macro 'uint128_t'
#define uint128_t unsigned __int128
                           ^
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1615:32: error: __int128 is not supported on this target
    DSIZE_T c2 = (DSIZE_T)a * (DSIZE_T)b;
                               ^
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:1606:18: note: expanded from macro 'DSIZE_T'
# define DSIZE_T uint128_t
                 ^
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:183:28: note: expanded from macro 'uint128_t'
#define uint128_t unsigned __int128
                           ^
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:2012:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/intern.h:35:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/st.h:58:45: error: 'st_check_for_sizeof_st_index_t' declared as an array with a negative size
typedef char st_check_for_sizeof_st_index_t[SIZEOF_VOIDP == (int)sizeof(st_index_t) ? 1 : -1];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19/ruby/config.h:63:22: note: expanded from macro 'SIZEOF_VOIDP'
#define SIZEOF_VOIDP 8
                     ^
6 errors generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

**Comment by legal90** [comment]
Hi @carcus88,

Does this issue still persist? With latest `nokogiri` 1.10.9 it seems working fine (macOS 10.15.3):
```
$ vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Fetching: mini_portile2-2.4.0.gem (100%)
Fetching: nokogiri-1.10.9.gem (100%)
Building native extensions.  This could take a while...
Fetching: vagrant-parallels-2.0.1.gem (100%)
```

**Comment by XXpE3** [comment]
I use macOS 10.15.4 vagrant 2.2.7, also cannot install `vagrant-parallels`.

```
Akari in ~(ruby-2.7.1) λ vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/xxpe3/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.9/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -r ./siteconf20200421-86698-1qiulct.rb extconf.rb
checking if the C compiler accepts -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/xxpe3/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.9 for inspection.
Results logged to /Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/gem_make.out
```

`nokogiri-1.10.9/gem_make.out`

```
current directory: /Users/xxpe3/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.9/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -r ./siteconf20200421-86698-1qiulct.rb extconf.rb
checking if the C compiler accepts -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1
```

**Comment by legal90** [comment]
@XXpE3 That error looks different from the first one. It seems that nokogiri extensions require Xcode Development Tools to be installed.

Could you please run `xcode-select --install` and then try to install the plugin again?

**Comment by XXpE3** [comment]
> @XXpE3 That error looks different from the first one. It seems that nokogiri extensions require Xcode Development Tools to be installed.
> 
> Could you please run `xcode-select --install` and then try to install the plugin again?

Hi, I have installed Command line tools `11.4.1`

```
Akari in ~(ruby-2.7.1) λ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by legal90** [comment]
@XXpE3 Sorry, I'm not sure that I can provide the good solution among the googling around :(

Based on replies in https://stackoverflow.com/questions/22413689/vagrant-cannot-install-nokogiri-dependent-plugins, I would recommend trying these options:
1) Delete `~/.vagrant/gem` directory and try to install the plugin again (beware that other plugins, if you have any, will be deleted too)

2) Installing the plugin with env variable `NOKOGIRI_USE_SYSTEM_LIBRARIES=1`:
```
export NOKOGIRI_USE_SYSTEM_LIBRARIES=1
vagrant plugin install vagrant-parallels 
``` 

3) Reinstall Xcode Development Tools
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```
and then try to install the plugin again

If nothing helps, then we should dig into the log `/Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/mkmf.log
` and find any clues there.

**Comment by XXpE3** [comment]
> @XXpE3 Sorry, I'm not sure that I can provide the good solution among the googling around :(
> 
> Based on replies in https://stackoverflow.com/questions/22413689/vagrant-cannot-install-nokogiri-dependent-plugins, I would recommend trying these options:
> 
> * Delete `~/.vagrant/gem` directory and try to install the plugin again (beware that other plugins, if you have any, will be deleted too)
> * OR Install the plugin with env variable `NOKOGIRI_USE_SYSTEM_LIBRARIES=1`:
> 
> ```
> export NOKOGIRI_USE_SYSTEM_LIBRARIES=1
> vagrant plugin install vagrant-parallels 
> ```
> 
> * OR reinstall Xcode Development Tools
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```
> 
> and then try to install the plugin again
> 
> If nothing helps, then we should dig into the log `/Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/mkmf.log ` and find any clues there.

Hi, I tried the steps, but I still get an error.

`nokogiri-1.10.9/mkmf.log`

```
Akari in ~(ruby-2.7.1) λ cat /Users/xxpe3/.vagrant.d/gems/2.4.9/extensions/x86_64-darwin-19/2.4.0/nokogiri-1.10.9/mkmf.log
"clang -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib     -lruby.2.4.9  -lpthread -ldl -lobjc  "
In file included from conftest.c:1:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

Thank you very much for your help :)

**Comment by romankulikov** [comment]
> ```
> In file included from conftest.c:1:
> In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
> In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
> /opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error: 'stdio.h' file not found
> #include <stdio.h>
>          ^~~~~~~~~
> 1 error generated.
> ```

Can you please verfiy  that macOS SDK installation is valid? `stdio.h` should be there:
```
% find /Library/Developer/CommandLineTools -name stdio.h
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
```

**Comment by XXpE3** [comment]
> > ```
> > In file included from conftest.c:1:
> > In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
> > In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
> > /opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error: 'stdio.h' file not found
> > #include <stdio.h>
> >          ^~~~~~~~~
> > 1 error generated.
> > ```
> 
> Can you please verfiy that macOS SDK installation is valid? `stdio.h` should be there:
> 
> ```
> % find /Library/Developer/CommandLineTools -name stdio.h
> /Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> ```

Hi, I gave it a try.

```
Akari in ~(ruby-2.7.1) λ find /Library/Developer/CommandLineTools -name stdio.h
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
```

**Comment by romankulikov** [comment]
> > > ```
> > > In file included from conftest.c:1:
> > > In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
> > > In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
> > > /opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error: 'stdio.h' file not found
> > > #include <stdio.h>
> > >          ^~~~~~~~~
> > > 1 error generated.
> > > ```
> > 
> > 
> > Can you please verfiy that macOS SDK installation is valid? `stdio.h` should be there:
> > ```
> > % find /Library/Developer/CommandLineTools -name stdio.h
> > /Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> > ```
> 
> 
> Hi, I gave it a try.
> 
> 
> ```
> Akari in ~(ruby-2.7.1) λ find /Library/Developer/CommandLineTools -name stdio.h
> /Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
> ```

It would be great to see the output of verbose compiler execution:
```
% clang -v -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib -lruby.2.4.9  -lpthread -ldl -lobjc
```

**Comment by romankulikov** [comment]
> It would be great to see the output of verbose compiler execution:
> ```
> % clang -v -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib -lruby.2.4.9  -lpthread -ldl -lobjc
> ```

Oops, forgot to mention that test file `conftest.c`
```
/* begin */
#include "ruby.h"
int main(int argc, char **argv)
{
  return 0;
}
/* end */
```
should be placed into current directory.

**Comment by XXpE3** [comment]
> > It would be great to see the output of verbose compiler execution:
> > ```
> > % clang -v -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib -lruby.2.4.9  -lpthread -ldl -lobjc
> > ```
> 
> Oops, forgot to mention that test file `conftest.c`
> 
> ```
> /* begin */
> #include "ruby.h"
> int main(int argc, char **argv)
> {
>   return 0;
> }
> /* end */
> ```
> 
> should be placed into current directory.

I gave it a try.

```
Akari in ~/Desktop(ruby-2.7.1) λ clang -v -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib -lruby.2.4.9  -lpthread -ldl -lobjc
Apple clang version 7.0.0  (based on LLVM 7.0.0)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin
 "/Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin/clang-7" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 520 -v -resource-dir /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/lib/clang/7.0.0 -I /opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I /opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I /opt/vagrant/embedded/include/ruby-2.4.0 -I . -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include -D _XOPEN_SOURCE -D _DARWIN_C_SOURCE -D _DARWIN_UNLIMITED_SELECT -D _REENTRANT -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 -fdebug-compilation-dir /Users/xxpe3/Desktop -ferror-limit 19 -fmessage-length 83 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fno-common -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/0q/4r3btnx157g4260lj5n1148c0000gn/T/conftest-0308fc.o -x c conftest.c
clang -cc1 version 7.0.0 based upon LLVM 7.0.0 default target x86_64-apple-darwin19.4.0
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19
 /opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward
 /opt/vagrant/embedded/include/ruby-2.4.0
 .
 /opt/vagrant/embedded/include
 /opt/vagrant/embedded/include/libxml2
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2
 /usr/local/include
 /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/lib/clang/7.0.0/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
In file included from conftest.c:2:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error:
      'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

Thank you very much for your help :)

**Comment by XXpE3** [comment]
```
Akari in ~/Desktop(ruby-2.7.1) λ swiftenv versions
  5.1.2
* 5.2.2 (set by /Users/xxpe3/Desktop/.swift-version)
Akari in ~/Desktop(ruby-2.7.1) λ clang -v -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/opt/vagrant/embedded/include -fno-common -pipe -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib -lruby.2.4.9  -lpthread -ldl -lobjc
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mframe-pointer=all -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 556.6 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3 -I /opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19 -I /opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I /opt/vagrant/embedded/include/ruby-2.4.0 -I . -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include -D _XOPEN_SOURCE -D _DARWIN_C_SOURCE -D _DARWIN_UNLIMITED_SELECT -D _REENTRANT -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include -I /opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 -internal-isystem /usr/local/include -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -internal-externc-isystem /usr/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -Wno-objc-signed-char-bool-implicit-int-conversion -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -fdebug-compilation-dir /Users/xxpe3/Desktop -ferror-limit 19 -fmessage-length 167 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fno-common -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/0q/4r3btnx157g4260lj5n1148c0000gn/T/conftest-a58156.o -x c conftest.c
clang -cc1 version 11.0.3 (clang-1103.0.32.59) default target x86_64-apple-darwin19.4.0
ignoring nonexistent directory "/usr/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
ignoring duplicate directory "/opt/vagrant/embedded/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/vagrant/embedded/include/ruby-2.4.0/x86_64-darwin19
 /opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward
 /opt/vagrant/embedded/include/ruby-2.4.0
 .
 /opt/vagrant/embedded/include
 /opt/vagrant/embedded/include/libxml2
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
In file included from conftest.c:2:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby.h:33:
In file included from /opt/vagrant/embedded/include/ruby-2.4.0/ruby/ruby.h:36:
/opt/vagrant/embedded/include/ruby-2.4.0/ruby/defines.h:101:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by romankulikov** [comment]
Well, these logs show something that I don't understand. I'm not Xcode guru so cannot provide fast and correct solution. Probably it is worth to search for an answer in some more specialised place.

What I cat suggest is to try to re-select toolchain:
```
% sudo xcode-select -s /Library/Developer/CommandLineTools
```
and then retry compiler invocation.

**Comment by XXpE3** [comment]
My guess is that there may be a problem with my system and I will continue to try other approaches.
Anyway, thank you very much for your help :)

**Comment by XXpE3** [comment]
Hi, I find that my Clang is not getting the correct SDK path.

```
Akari in ~(ruby-2.7.1) λ clang++ -E -x c++ - -v < /dev/null
Apple clang version 7.0.0  (based on LLVM 7.0.0)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin
 "/Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin/clang-7" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 520 -v -resource-dir /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/lib/clang/7.0.0 -stdlib=libc++ -internal-isystem /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin/../include/c++/v1 -fdeprecated-macro -fdebug-compilation-dir /Users/xxpe3 -ferror-limit 19 -fmessage-length 167 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 7.0.0 based upon LLVM 7.0.0 default target x86_64-apple-darwin19.4.0
ignoring nonexistent directory "/usr/include/c++/v1"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/bin/../include/c++/v1
 /usr/local/include
 /Library/Developer/Toolchains/swift-5.1.2-RELEASE.xctoolchain/usr/lib/clang/7.0.0/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 400 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

So I tried to modify it.

`export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"`

Then it's ready to install properly.

```
Akari in ~(ruby-2.7.1) λ export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
Akari in ~(ruby-2.7.1) λ vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Fetching: vagrant-parallels-2.0.1.gem (100%)
Installed the plugin 'vagrant-parallels (2.0.1)'!
```

Thank you so much for your help and patience.
I hope this helps others as well.

**Comment by RomaJZ** [comment]
@XXpE3 Hi! I've tried your solution, but it didn't work for me. I've also done every step before, but the output is still the same:
`romajz@MacBook-Pro-Roma ~ % vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20200506-1021-115whje.rb extconf.rb
checking if the C compiler accepts -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9 for inspection.
Results logged to /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/gem_make.out
`
Could you help me, please?

**Comment by RomaJZ** [comment]
@XXpE3 Hi! I've tried your solution, but it didn't work for me. I've also done every step before, but the output is still the same:
```
romajz@MacBook-Pro-Roma ~ % vagrant plugin install vagrant-parallels
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20200506-1021-115whje.rb extconf.rb
checking if the C compiler accepts -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9 for inspection.
Results logged to /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/gem_make.out
```

Could you help me, please?

**Comment by rloomans** [comment]
I have the same problem where compile can't find stdio.h.

I found that the ruby packaged with vagrant has hard coded paths to the SDK in /opt/vagrant/embedded/lib/ruby/2.6.0/x86_64-darwin19/rbconfig.rb

```
$ grep 10.9.sdk /opt/vagrant/embedded/lib/ruby/2.6.0/x86_64-darwin19/rbconfig.rb 
  CONFIG["configure_args"] = " '--prefix=/opt/vagrant/embedded' '--disable-debug' '--disable-dependency-tracking' '--disable-install-doc' '--enable-shared' '--with-opt-dir=/opt/vagrant/embedded' '--enable-load-relative' 'CFLAGS=-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk' 'LDFLAGS= -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk' 'CPPFLAGS=-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk' 'CXXFLAGS=-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk'"
  CONFIG["DLDFLAGS"] = " -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/opt/vagrant/embedded/lib"
  CONFIG["CXXFLAGS"] = "-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk"
  CONFIG["CPPFLAGS"] = "-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk -I/opt/vagrant/embedded/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags)"
  CONFIG["LDFLAGS"] = "-L.  -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk -fstack-protector-strong -L/opt/vagrant/embedded/lib"
  CONFIG["CFLAGS"] = "-I/opt/vagrant/embedded/include -mmacosx-version-min=10.9 -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk -fno-common -pipe"
```

Looks like it's a vagrant packaging problem.

My workaround was to download the the 10.9 SDK and drop it into /Users/vagrant/SDKs/MacOSX10.9.sdk

**Comment by RomaJZ** [comment]
@rloomans But as I checked there is no such directory /Users/vagrant/ 
So I don't think that's the proper way to do it

**Comment by rloomans** [comment]
> @rloomans But as I checked there is no such directory /Users/vagrant/
> So I don't think that's the proper way to do it

It's definitely not the right way to do it: the vagrant package needs to be fixed.

However it does get the provider working and gets me out of a hole :).

**Comment by RomaJZ** [comment]
@rloomans So you just created that folder and everything worked fine?

**Comment by rloomans** [comment]
> @rloomans So you just created that folder and everything worked fine?

No... I downloaded the 10.9 SDK from [https://github.com/phracker/MacOSX-SDKs](https://github.com/phracker/MacOSX-SDKs) and placed it in that folder.

**Comment by RomaJZ** [comment]
@rloomans Yes, I mean that. Thank you!

**Comment by adambreen** [comment]
@RomaJZ: I think that @rloomans must have manually created the /Users/vagrant (and /Users/vagrant/SDKs) folder. I did this, chown-ed them to my current user, and was able to get the damn thing to build. This is CLEARLY not a good implementation. 

@legal90 please note that I got exactly the same results as @rloomans. The issue is that there is a hardcoded path to /Users/vagrant/SDKs, perhaps a legacy from previous Vagrant versions?

I am running OS X 10.15.4. For completeness, I have the full XCode Version 11.4.1 (11E503a) installed.

❯ xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk

**Comment by XXpE3** [comment]
> @XXpE3 Hi! I've tried your solution, but it didn't work for me. I've also done every step before, but the output is still the same:
> 
> ```
> romajz@MacBook-Pro-Roma ~ % vagrant plugin install vagrant-parallels
> Installing the 'vagrant-parallels' plugin. This can take a few minutes...
> Building native extensions. This could take a while...
> Vagrant failed to properly resolve required dependencies. These
> errors can commonly be caused by misconfigured plugin installations
> or transient network issues. The reported error is:
> 
> ERROR: Failed to build gem native extension.
> 
>     current directory: /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9/ext/nokogiri
> /opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20200506-1021-115whje.rb extconf.rb
> checking if the C compiler accepts -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include/libxml2 -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
> 	--help
> 	--clean
> /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
> 	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:532:in `with_werror'
> 	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
> 	from extconf.rb:138:in `nokogiri_try_compile'
> 	from extconf.rb:162:in `block in add_cflags'
> 	from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:643:in `with_cflags'
> 	from extconf.rb:161:in `add_cflags'
> 	from extconf.rb:416:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Users/romajz/.vagrant.d/gems/2.6.6/gems/nokogiri-1.10.9 for inspection.
> Results logged to /Users/romajz/.vagrant.d/gems/2.6.6/extensions/x86_64-darwin-19/2.6.0/nokogiri-1.10.9/gem_make.out
> ```
> 
> Could you help me, please?

Sorry, I just saw your comment. Looks like you have the same problem I do. You just need to set the SDKROOT path manually.

```
Akari in ~(ruby-2.7.1) λ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Akari in ~(ruby-2.7.1) λ export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
Akari in ~(ruby-2.7.1) λ vagrant plugin install vagrant-parallels
==> vagrant: A new version of Vagrant is available: 2.2.8 (installed version: 2.2.7)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Installed the plugin 'vagrant-parallels (2.0.1)'!
```

**Comment by legal90** [comment]
@adambreen Correct, that's the issue of embedded Vagrant ruby, which is managed within this project: https://github.com/hashicorp/vagrant-installers 
We can't  do anything with that here, in vagrant-parallels.

Please refer to this issue and put your findings there:
https://github.com/hashicorp/vagrant-installers/issues/163

**Comment by adambreen** [comment]
Ok will do thanks!

**Comment by legal90** [comment]
The issue has been fixed in Vagrant 2.2.9:
https://github.com/hashicorp/vagrant-installers/issues/163#issuecomment-625503064

**Comment by carcus88** [comment]
Just an update to my previous comment where this is still broken it seems in in 2.2.9.
I tried the 2.2.10 dev release and found the issue still exists there as well even though it seems to be marked as resolved. After more digging I found some reference to 2.2.6 in 

https://github.com/hashicorp/vagrant/issues/11619 

I was able to successfully install and use vagrant-paralllels using the following vagrant build

https://github.com/hashicorp/vagrant-installers/releases/tag/v2.2.6%2Bbuild-updates
